// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitOfWorkDemo.Infrastructure;

#nullable disable

namespace PMS.Infrastructure.Migrations
{
    [DbContext(typeof(DbContextClass))]
    [Migration("20231114135107_addRecord")]
    partial class addRecord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PMS.Core.Models.PatientRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal?>("BMI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bht")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BloodLossInTheDrainD1_D2")
                        .HasColumnType("int");

                    b.Property<int?>("BloodLossInTheDrainD2")
                        .HasColumnType("int");

                    b.Property<bool?>("BoneAvolsion")
                        .HasColumnType("bit");

                    b.Property<int?>("ChestComplications_1st")
                        .HasColumnType("int");

                    b.Property<int?>("ChestComplications_2st")
                        .HasColumnType("int");

                    b.Property<int?>("ChestComplications_Intermediate")
                        .HasColumnType("int");

                    b.Property<int?>("ChestComplications_Late")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("DLD")
                        .HasColumnType("bit");

                    b.Property<bool?>("DM")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateofSurgery")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeepWoundInfections_1st")
                        .HasColumnType("int");

                    b.Property<int?>("DeepWoundInfections_2nd")
                        .HasColumnType("int");

                    b.Property<int?>("DeepWoundInfections_Intermediate")
                        .HasColumnType("int");

                    b.Property<int?>("DeepWoundInfections_Late")
                        .HasColumnType("int");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EffectivenessInMobilization")
                        .HasColumnType("int");

                    b.Property<int?>("FatEmbolism_1st")
                        .HasColumnType("int");

                    b.Property<int?>("FatEmbolism_2st")
                        .HasColumnType("int");

                    b.Property<int?>("FatEmbolism_Intermediate")
                        .HasColumnType("int");

                    b.Property<int?>("FatEmbolism_Late")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<int?>("Height_cm")
                        .HasColumnType("int");

                    b.Property<int?>("Hematoma_1st")
                        .HasColumnType("int");

                    b.Property<int?>("Hematoma_2st")
                        .HasColumnType("int");

                    b.Property<int?>("Hematoma_Intermediate")
                        .HasColumnType("int");

                    b.Property<int?>("Hematoma_Late")
                        .HasColumnType("int");

                    b.Property<bool?>("Hepato_Gastrointestinal")
                        .HasColumnType("bit");

                    b.Property<string>("HxOfOtherMSKInjuriesAndPains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Hypertension")
                        .HasColumnType("bit");

                    b.Property<string>("IatrogenicFactors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndicationForAdmissionToTheICU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IschemicHeartDiseases")
                        .HasColumnType("bit");

                    b.Property<bool?>("LigametAvulsions")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("N0ofPostOpFFPTransfussions")
                        .HasColumnType("int");

                    b.Property<int?>("NOofPostOpBloodTransfussions")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoofDaysInTheHospital")
                        .HasColumnType("int");

                    b.Property<int?>("NoofDaysInTheICU")
                        .HasColumnType("int");

                    b.Property<string>("Other1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OtherBoneDissordersInLimbs_congenital")
                        .HasColumnType("bit");

                    b.Property<bool?>("OtherBoneDissordersInLimbs_traumatic")
                        .HasColumnType("bit");

                    b.Property<string>("Others")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PainTolerance_PostOpD1")
                        .HasColumnType("int");

                    b.Property<int?>("PainTolerance_beforeDischarge")
                        .HasColumnType("int");

                    b.Property<int>("PatientCategories")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PerOperativeBloodLoss")
                        .HasColumnType("int");

                    b.Property<bool?>("PeripheralNeuropathies")
                        .HasColumnType("bit");

                    b.Property<int?>("PostOpD3BP")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD3BloodUrea")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD3FBS")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD3HB")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD3HR")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD3NeutrophilCount_103_uL")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD3RR")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD3SerumCreatinine")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD3SerumK")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD3SerumNa")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD3WBC")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD5BP")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD5BloodUrea")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD5FBS")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD5HB")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD5HR")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD5Neutrophil")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD5RR")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD5SerumCreatinine")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD5SerumK")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD5SerumNa")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpD5WBC")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpDay1BP")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpDay1BloodUrea")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpDay1FBS_mg_dL")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpDay1HB")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpDay1HR")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpDay1Neutrophil")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpDay1RR")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpDay1SerumCreatinine")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpDay1SerumK")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpDay1SerumNa")
                        .HasColumnType("int");

                    b.Property<int?>("PostOpDay1WBC")
                        .HasColumnType("int");

                    b.Property<int?>("PreOpBP_mmHg")
                        .HasColumnType("int");

                    b.Property<int?>("PreOpBloodUrea_mg_dL")
                        .HasColumnType("int");

                    b.Property<int?>("PreOpFBS_mg_dL")
                        .HasColumnType("int");

                    b.Property<int?>("PreOpHB_g_dL")
                        .HasColumnType("int");

                    b.Property<int?>("PreOpHR_bpm")
                        .HasColumnType("int");

                    b.Property<int?>("PreOpK")
                        .HasColumnType("int");

                    b.Property<int?>("PreOpNa")
                        .HasColumnType("int");

                    b.Property<int?>("PreOpNeutrophilCount")
                        .HasColumnType("int");

                    b.Property<int?>("PreOpRR_bpm")
                        .HasColumnType("int");

                    b.Property<int?>("PreOpSCcreatinine")
                        .HasColumnType("int");

                    b.Property<int?>("PreOpWBC_103")
                        .HasColumnType("int");

                    b.Property<int?>("QuadricepMuscleRupture_1st")
                        .HasColumnType("int");

                    b.Property<int?>("QuadricepMuscleRupture_2st")
                        .HasColumnType("int");

                    b.Property<int?>("QuadricepMuscleRupture_Intermediate")
                        .HasColumnType("int");

                    b.Property<int?>("QuadricepMuscleRupture_Late")
                        .HasColumnType("int");

                    b.Property<bool?>("Renal")
                        .HasColumnType("bit");

                    b.Property<bool?>("Respiratory")
                        .HasColumnType("bit");

                    b.Property<int?>("SkinOpening_1st")
                        .HasColumnType("int");

                    b.Property<int?>("SkinOpening_2st")
                        .HasColumnType("int");

                    b.Property<int?>("SkinOpening_Intermediate")
                        .HasColumnType("int");

                    b.Property<int?>("SkinOpening_Late")
                        .HasColumnType("int");

                    b.Property<bool?>("Stroke")
                        .HasColumnType("bit");

                    b.Property<int?>("SuperficialWoundInfections_1st")
                        .HasColumnType("int");

                    b.Property<int?>("SuperficialWoundInfections_2nd")
                        .HasColumnType("int");

                    b.Property<int?>("SuperficialWoundInfections_Intermediate")
                        .HasColumnType("int");

                    b.Property<int?>("SuperficialWoundInfections_Late")
                        .HasColumnType("int");

                    b.Property<string>("Surgery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SurgicalWoundComplication_1st")
                        .HasColumnType("int");

                    b.Property<int?>("SurgicalWoundComplication_2st")
                        .HasColumnType("int");

                    b.Property<int?>("SurgicalWoundComplication_Intermediate")
                        .HasColumnType("int");

                    b.Property<int?>("SurgicalWoundComplication_Late")
                        .HasColumnType("int");

                    b.Property<bool?>("Thyroid")
                        .HasColumnType("bit");

                    b.Property<int?>("TorniquetTimeMin")
                        .HasColumnType("int");

                    b.Property<int?>("TotalOperativeRoomTime_min")
                        .HasColumnType("int");

                    b.Property<bool>("TranexamicAcidGivenOrNot")
                        .HasColumnType("bit");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<int?>("Weight_kg")
                        .HasColumnType("int");

                    b.Property<string>("other")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PatientRecord");
                });

            modelBuilder.Entity("UnitOfWorkDemo.Core.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContactNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmergencyContactNo")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
